# Generated by Django 4.2.28 on 2026-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        # Nullable, no default, no backfill: Postgres records this in the
        # catalogue without rewriting the table, and old application code that
        # never selects the column is unaffected.
        migrations.AddField(
            model_name='issue',
            name='last_synced_at',
            field=models.DateTimeField(null=True),
        ),
    ]
