# Generated by Django 4.2.28 on 2026-09-29 10:05

from django.db import migrations, models


def strip_legacy_html(apps, schema_editor):
    Issue = apps.get_model('db', 'Issue')
    # Loads every issue in the table into memory in one transaction.
    for issue in Issue.objects.all():
        issue.description_stripped = ''
        issue.save(update_fields=['description_stripped'])


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        # Irrecoverably discards production content.
        migrations.RemoveField(
            model_name='issue',
            name='description_html',
        ),
        # NOT NULL with a default: rewrites the whole table under an ACCESS
        # EXCLUSIVE lock on older Postgres, and old application code still
        # running during the rolling deploy never populates it.
        migrations.AddField(
            model_name='issue',
            name='sync_state',
            field=models.CharField(default='pending', max_length=32),
            preserve_default=False,
        ),
        # No reverse: a failed deploy cannot be rolled back.
        migrations.RunPython(strip_legacy_html),
    ]
